/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedChatsChatIdRouteImport } from './routes/_authenticated/chats.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatsRoute,
} as any)
const AuthenticatedChatsChatIdRoute =
  AuthenticatedChatsChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => AuthenticatedChatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof AuthenticatedChatsRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRoute
  '/_authenticated/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats'
    | '/perfil'
    | '/stories'
    | '/chats/$chatId'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/perfil' | '/stories' | '/chats/$chatId' | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chats'
    | '/_authenticated/perfil'
    | '/_authenticated/stories'
    | '/_authenticated/chats/$chatId'
    | '/_authenticated/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
    '/_authenticated/chats/$chatId': {
      id: '/_authenticated/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AuthenticatedChatsChatIdRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
  }
}

interface AuthenticatedChatsRouteChildren {
  AuthenticatedChatsChatIdRoute: typeof AuthenticatedChatsChatIdRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedChatsRouteChildren: AuthenticatedChatsRouteChildren = {
  AuthenticatedChatsChatIdRoute: AuthenticatedChatsChatIdRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedChatsRouteWithChildren =
  AuthenticatedChatsRoute._addFileChildren(AuthenticatedChatsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatsRoute: AuthenticatedChatsRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
